"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = "catppuccin_macchiato"

format = """
$username$localip:$directory\
$git_branch\
$git_status\
$c\
$cpp\
$cmake\
$dart\
$deno\
$rust\
$nodejs\
$php\
$java\
${custom.java}\
${custom.kotlin}\
$gradle\
$python\
$julia\
$golang\
$scala\
$swift\
$perl\
$conda\
$lua\
$aws\
$sudo\
$container\
$docker_context\
$character"""

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)'

[username]
show_always = true
style_user = "fg:blue"
style_root = "fg:blue"
format = '[$user@](bold green)'

[localip]
ssh_only = false
style = "fg:surface0"
format = '[$localipv4](bold cyan)'
disabled = false

[directory]
style = "fg:peach"
format = "[$path ](bold blue)"
truncate_to_repo = false

# Git 
[git_branch]
symbol = ""
style = "fg:teal"
format = '[[\( $symbol $branch \) ](fg:bold white)]($style)'

[git_status]
style = "fg:teal"
format = '[[($all_status$ahead_behind )](fg:white)]($style)'

# Languages
[nodejs]
symbol = ""
style = "fg:teal"
format = '[[$symbol( $version) ](fg:teal)]($style)'

[c]
symbol = ""
style = "fg:teal"
format = '[[$symbol( $version) ](fg:teal)]($style)'

[cpp]
symbol = ""

[cmake]
symbol = ""

[rust]
symbol = "󱘗"
style = "fg:teal"
format = '[[$symbol( $version) ](fg:teal)]($style)'

[golang]
symbol = ""
style = "fg:teal"
format = '[[$symbol( $version) ](fg:teal)]($style)'

[java]
symbol = ""
style = "fg:teal"
format = '[[\($symbol( $version)\) ](fg:red)]($style)'

[gradle]
symbol = ""
format = '[$symbol( $version) ]($style)'

[dart]
symbol = ""
format = '[$symbol($version )](bold black)'

[python]
symbol = ""
style = "fg:teal"
format = '[[$symbol( $version) ](fg:yellow)]($style)'

[lua]
symbol = "󰢱"
style = "fg:teal"
format = '[[$symbol( $version) ](fg:teal)]($style)'

[gcloud]
symbol = '☁️ '
format = 'on [$symbol$account(@$domain)(\($region\))]($style) '

[docker_context]
symbol = ""
style = "fg:mantle"
format = '[[$symbol( $context) ](fg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:peach"
format = '[[  $time ](fg:purple)]($style)'

[custom.kotlin]
detect_files = [ "build.gradle", "build.gradle.kts" ]
command = "~/.config/starship/scripts/kotlin_version"
symbol = ""
format = '[[$symbol( $output) ](fg:yellow)]($style)'

[custom.java]
command = "~/.config/starship/scripts/java_version"
detect_files = [ "build.gradle", "build.gradle.kts" ]
symbol = ""
format = "[$symbol $output ](fg:red)"

# [custom.sample]
# detect_files = [ "build.gradle", "build.gradle.kts" ]
# detect_folders = [ ".git" ]
# style = "bold blue"
# symbol = "-"
# command = "echo hi"
# format = "[$symbol $output ]($style)"
